import './globals.css'

import Nav from './components/Nav'
import { getServerSession } from 'next-auth/next'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Hydrate from './components/Hydrate'
import {Roboto} from 'next/font/google'

// define main font
const roboto = Roboto({weight: ['300', '400', '500', '700'], subsets: ['latin']})

export const metadata = {
  title: 'Next Ecommerce',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // Fetch the User

  const session = await getServerSession(authOptions)
  // console.log(session);
  

  return (
    <html lang="en">
      <body className={`xl:mx-96 lg:mx-32 md:mx-24 sm:mx-12 ${roboto.className}`}>
        <Hydrate>
          <Nav
            user={session?.user}
            expires={session?.expires as string}
          />
          {children}
        </Hydrate>
      </body>
    </html>
  )
}
